name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rustfmt:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@master
        with:
          command: fmt
          args: --all -- --check --verbose
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: actions-rs/clippy-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --tests -- -D warnings
